- theme/themes/eea/extras/header.less
- theme/themes/eea/extras/header.variables
This prevents entangling of toolbar with header top-bar
p
> fix z-index of header top-bar

- theme/themes/eea/tokens/fonts.less
https://taskman.eionet.europa.eu/issues/148554
> Design Tokens - Fonts

- src/ui/Header/Header.jsx
- src/ui/Header/Header.stories.js
- src/ui/Header/HeaderMenuPopUp.js
https://taskman.eionet.europa.eu/issues/147802#note-26
https://62713c57bcbdf4004a3d99b8-nsbkddprjs.chromatic.com/?path=/story/layout-header--default
> [R2] Mega Menu version 2

- src/ui/Accordion/Accordion.stories.js
- src/ui/CallToAction/CallToAction.stories.jsx
- src/ui/Header/Header.jsx
- src/ui/Header/Header.stories.js
- src/ui/Header/HeaderMenuPopUp.js
- theme/themes/eea/elements/button.overrides
- theme/themes/eea/globals/site.variables
- theme/themes/eea/modules/accordion.overrides
- theme/themes/eea/modules/accordion.variables
https://taskman.eionet.europa.eu/issues/151844
https://taskman.eionet.europa.eu/issues/151845
https://62713c57bcbdf4004a3d99b8-hxcjunvdqs.chromatic.com/?path=/story/components-call-to-action--default
https://62713c57bcbdf4004a3d99b8-hxcjunvdqs.chromatic.com/?path=/story/components-accordion--default&args=variant:default
> Call to Action & Accordion: Primary and Tertiary variation

- package.json
- src/ui/Card/Card.stories.jsx
- theme/themes/eea/globals/site.overrides
- theme/themes/eea/globals/utilities.less
- theme/themes/eea/views/card.overrides
- theme/themes/eea/views/card.variables
Added also dependency on slick-carousel for the theming of the slick pagination
> refactor(card): theming implementation to allow has theming classes

- website/docs/webdev/3-Guidelines/3-images.md
- website/docs/webdev/md_components/media_container_image_components/usage_markdown.md
- website/docs/webdev/md_components/page_header_components/usage_markdown.md
https://taskman.eionet.europa.eu/issues/153542
https://ci.eionet.europa.eu/job/volto-addons/job/volto-eea-design-system/job/PR-257/2/volto-eea-design-system/
> [Docusaurus] - Image copyright information

- src/ui/ContextNavigation/ContextNavigation.stories.jsx
Task #150880 - https://taskman.eionet.europa.eu/issues/150880
default title is a 'Navigation' text
if a custom title is set, it transforms it in a link as in [Volto ContextNavigation.jsx](https://github.com/plone/volto/blob/master/src/components/theme/Navigation/ContextNavigation.jsx#L80)
Changed storybook to respect block's title change.
> Default title is text, custom title is link

- theme/themes/eea/extras/banner.variables
https://taskman.eionet.europa.eu/issues/160847
> update green color used in page header to the new EEA green

- src/ui/Card/Card.stories.jsx
- theme/themes/eea/views/card.overrides
- theme/themes/eea/views/card.variables
Taskman comment: https://taskman.eionet.europa.eu/issues/155228#note-37
Teaser card grid:
https://62713c57bcbdf4004a3d99b8-uwjlyhawef.chromatic.com/?path=/story/components-card-default--teaser-card-grid
> new card variation with title on top of image (cards overflow on tablet issue)

- src/ui/Footer/FooterHeader.jsx
- theme/themes/eea/extras/footer.less
- theme/themes/eea/extras/footer.variables
No known ticket, fix requested in chat after testing with Wave evaluation tool plugin
https://62713c57bcbdf4004a3d99b8-fnqyaurqie.chromatic.com/?path=/story/layout-footer--default
> [Accessibility] Footer: update p with h3 heading tag for theme sites title

- src/ui/Accordion/Accordion.stories.js
- src/ui/Header/Header.stories.js
- src/ui/Header/HeaderMenuPopUp.js
- src/ui/Logo/Logo.jsx
- theme/themes/eea/extras/header.less
- theme/themes/eea/extras/header.variables
- theme/themes/eea/globals/site.overrides
- theme/themes/eea/globals/site.variables
- theme/themes/eea/modules/accordion.overrides
https://taskman.eionet.europa.eu/issues/161350
Accordion updated with box-shadow
https://62713c57bcbdf4004a3d99b8-rtsfxcxjle.chromatic.com/?path=/story/components-accordion--default
Mega menu updated with box-shadow
https://62713c57bcbdf4004a3d99b8-rtsfxcxjle.chromatic.com/?path=/story/layout-header--default
Footer links box-shadow
https://62713c57bcbdf4004a3d99b8-rtsfxcxjle.chromatic.com/?path=/story/layout-footer--default
> [Accessibility] - Accordion

- src/ui/Accordion/Accordion.stories.js
- theme/themes/eea/modules/accordion.overrides
Comment: https://taskman.eionet.europa.eu/issues/147811#note-24
https://62713c57bcbdf4004a3d99b8-rmwugplmpy.chromatic.com/?path=/story/components-accordion--default
> [Accordion] Add control to change the heading tag of the title

- src/ui/Footer/Contact.jsx
- src/ui/Footer/Footer.stories.js
fix: Added a check if urls in Contact component are internal or not. #250343
> fix: Check contact url if is internal #250343

- website/docs/webdev/5-Components/29-Video.mdx
- website/docs/webdev/md_components/video_components/showcase_markdown.md
- website/docs/webdev/md_components/video_components/usage_markdown.md
https://taskman.eionet.europa.eu/issues/250783#change-808534
Docusaurus: https://ci.eionet.europa.eu/job/volto-addons/job/volto-eea-design-system/job/PR-343/2/volto-eea-design-system/
> [Docusaurus] Add Video block to storybook/docusaurus based on existing Volto EEA add-on

- src/helpers/index.js
- src/helpers/useFirstVisited.js
- src/helpers/useOnScreen.js
- src/ui/Footer/Footer.jsx
- theme/themes/eea/extras/footer.less
I fixed: the footer background images should remain when the element enters for the first time in the viewport
In addition, I made sure that the footer-no-bg and footer-wrapper have the same padding
> (fix):Stop image disappear over and over ref253080

- theme/themes/eea/extras/header.less
- theme/themes/eea/extras/header.variables
- refs [#253352](https://taskman.eionet.europa.eu/issues/253352)
> Fix subsite z-index to make it clickable

- theme/themes/eea/globals/site.overrides
Needs first https://github.com/plone/volto/pull/4847
> fix(stylemenu): remove generic css selectors in favour of specific class

- src/helpers/eventHandlers.js
- src/helpers/index.js
- src/ui/Header/HeaderSearchPopUp.js
- theme/themes/eea/elements/input.overrides
https://taskman.eionet.europa.eu/issues/254316
> [ACCESSIBILITY 2.1.1.1] Common elements - Search input icon

- Jenkinsfile
- Makefile
Fix for stylint issues, implementing solution suggest by Valentina with new syntax.
> Update Makefile for current stylelint syntax

- theme/themes/eea/globals/site.variables
- theme/themes/eea/tokens/colors.less
- website/docs/webdev/3-Guidelines/2-colours.mdx
- website/docs/webdev/3-Guidelines/_partials/_markdown-eea-color-palette.mdx
- website/src/css/custom.css
Related ticket: https://taskman.eionet.europa.eu/issues/257841
Docusaurus:  https://ci.eionet.europa.eu/job/volto-addons/job/volto-eea-design-system/job/PR-401/2/volto-eea-design-system/
Storybook: https://62713c57bcbdf4004a3d99b8-cfstrojeye.chromatic.com/?path=/story/components-accordion--default
> Contrast issue with WISE blue

- theme/themes/eea/modules/search.overrides
This fix is for https://taskman.eionet.europa.eu/issues/258078#change-852863. Also there is a fix in volto: https://github.com/plone/volto/pull/5305
> (Fix) : Put padding in facets select refs 258078

- theme/themes/eea/extras/inpageNavigation.less
https://taskman.eionet.europa.eu/issues/261560
> (fix): Make inpage-navigation not visibile on edit sidebar

- .eslintrc.js
- src/ui/Footer/FooterActions.jsx
- src/ui/Header/Header.stories.js
- src/ui/NewTabLabeledIcon/NewTabLabeledIcon.jsx
- website/docusaurus.config.js
> fix: remove noreferrer for seo purposes

- src/ui/Footer/Contact.jsx
- src/ui/Footer/Footer.jsx
- src/ui/Footer/Footer.stories.js
- src/ui/Footer/Footer.stories.test.js
- src/ui/Footer/FooterSitesButton.jsx
- src/ui/Footer/Social.jsx
- src/ui/Footer/SubFooter.jsx
- theme/themes/eea/extras/footer.less
- theme/themes/eea/extras/footer.variables
https://taskman.eionet.europa.eu/issues/265857
> Footer simplification according to the 265857
